Repository cs-dept-ibbul/vlab, pull requests merged in 2021-03, with the labels that each got.

#44 Feat: modified navbar
  public/css/app.css
  public/css/style.css
  public/fonts/AvenirNextCyr-Bold.ttf
  public/fonts/AvenirNextCyr-Demi.ttf
  public/fonts/AvenirNextCyr-Heavy.ttf
  public/fonts/AvenirNextCyr-Italic.ttf
  public/fonts/AvenirNextCyr-Light.ttf
  public/fonts/AvenirNextCyr-Medium.ttf
  public/fonts/AvenirNextCyr-Regular.ttf
  public/fonts/AvenirNextCyr-Thin.ttf
  public/fonts/AvenirNextCyr-UltraLight.ttf
  public/js/app.js
  resources/js/components/Navbar.vue
  resources/js/components/VewCourse.vue
  resources/js/views/app.vue
  resources/js/views/pages/Explore.vue
  resources/js/views/pages/Home.vue
  resources/sass/app.scss
  resources/views/explore.blade.php
  resources/views/root.blade.php
  yarn.lock
Labels: enhancement, frontend

#53 created admin view-Students-dashboard and reformat color
  public/css/style.css
  public/images/user-graduate-solid.svg
  public/js/app.js
  resources/js/app.js
  resources/js/components/CoursesTab.vue
  resources/views/admin/ViewStudentsdashboard.blade.php
Labels: frontend

#59 feat: course upload and student import.
  .DS_Store
  app/Http/Controllers/Api/CourseController.php
  app/Http/Controllers/Api/UserController.php
  app/Http/Controllers/Api/Util.php
  app/Models/Course.php
  database/migrations/2014_10_12_000000_create_users_table.php
  database/migrations/2021_02_14_150913_create_courses_table.php
  public/.DS_Store
  public/students/.DS_Store
  public/students/data.csv
  routes/api.php
Labels: backend
